### ISSUE TITLE
Suggested edits to ontology-curator-go-style.md

### ISSUE THREAD

**Issue by dosumis** [OBOAcademy/obook#110]
The new editor pathway material is a good start but is quite jumbled.  The first doc on the pathway is a a pretty big involved tutorial and should be marked as such.  It's not a great document for reference, but could be mined for material that is.

I suggest explicitly structuring the doc as an editor's manual suggest and separating out ontology editing from pipeline/workflow and GitHub issues. Ontology editing reference should be linked to lessons that given some background/theory.

Here's my attempt at a quick sketch of structure

Protege basics  (we can also link to content here - https://protegewiki.stanford.edu/wiki/Protege4UserDocs#Editor_features - only partly out of date)
   - Active Ontology Tab 
      - Ontology level metadata and imports
   - Search
   - Entities Class View & component tabs
      --> Browsing the ontology +/- reasoning
   - DL query editor
   - Editing
      - Adding, editing, annotating and deleting axioms
      - class expression editor & autocomplete
      - linking OWL entities via annotation properties
  -  Adding new term: 
        - via the tree editor
        - via the class expression editor
  - Adding logical axioms to classes (Maybe move this down 
  - Adding disjointness

- Logical axiomatization of classes & use of reasoning 
     - Some basics on adding logical axioms --> link to theory refs. 
     - Keeping it simple
       - Keeping inside the EL profile
       - Simple (non-nested) class expressions
       - Nested class expressions 
          - limitations for OBO pathway
          - composed entities following the schemas of other ontologies (GO example)

- Ontology relations (high level guide to the most broadly used relations - individual ontologies likely need their own guides that focus on the sets of relations they use.)
   - part_of/has_part & overlap
   - has_characteristic/characteristic_of
   - capable_of/capable_of_part_of
   - taxon restrictions
      - theory and practice
      ---> Link to relevant pipeline ODK docs

OBO-stye term annotation
  - What annotations to add to a term:
     - One rdsf:label
     - One definition - annotated with a database_cross_reference -> source
        -  Link to doc on writing good definitions
     - One rdfs:comment (optional)
        - Link to doc on types of comments
     - zero -> many synonyms, various types (link to central doc on this)
     - zero -> many database_cross_references
     - subsets 
     - database_cross_references

Term merging and obsoletion:
 - When to merge, when to obsolete
 - Practical guide to merging and obsoletion

Efficient addition of new terms using duplication:
 - Practicalities and dangers

**Comment by shawntanzk** [comment]
A few questions:
1) should relations get taught above editing? I remember @dosumis going through that with me very early on
2) should curators handle import management and templates?

Here's my strategy for getting to the above:
I'll create a draft PR with the above headers in the pathway, and we can start creating documents and merging them into main (without linking for now). On each PR I'll add the links (updating with main) on the draft PR to keep track of it. Once everything is together, we can push through that PR with the links all in place.
