### ISSUE TITLE
DL query tutorial

### ISSUE THREAD

**Issue by shawntanzk** [OBOAcademy/obook#114]
Putting this ticket out to see if anyone has a good tutorial/how-to/reference for DL queries (rather not reinvent the wheel and all) 
Tagging people who might have one/might know where to find one (please help me tag others if you think they might too).
@dosumis @cmungall @matentzn @nicolevasilevsky @sabrinatoro

**Comment by nicolevasilevsky** [comment]
@shawntanzk this was adapted from a tutorial that was originally created by Chris and some others:
https://ontology101tutorial.readthedocs.io/en/latest/DL_QueryTab.html

**Comment by shawntanzk** [comment]
yesss! that looks perfect! thanks so much @nicolevasilevsky :D

**Comment by nicolevasilevsky** [comment]
can we make sure we properly acknowledge the original creators: Nicole Vasilevsky, Melissa Haendel, Chris Mungall, David Osumi-Sutherland, Matt Yoder, Carlo Torniai, and Simon Jupp
thanks! :)

**Comment by shawntanzk** [comment]
defs! I was going to link back to the page, but will also add the creators names :)
