### ISSUE TITLE
How to create a new ontology from scratch with data or metadata

### ISSUE THREAD

**Issue by S2Ola** [OBOAcademy/obook#123]
**Tutorial Request:**

I am interested in learning how ontologies are created from data, ,as I see many tutorial starting off with one or more ontologies at the start of ontology creation.  I am faced with such problem as having just a list of controlled vocabularies and terminologies, how do / should I create an ontology from such data and metadata if there are no existing ontologies in the domain?

**Comment by matentzn** [comment]
Thank you @S2Ola 

We just changed our system for requesting tutorials, can you copy your request here https://github.com/OBOAcademy/obook/discussions and close this issue please?

**Comment by S2Ola** [comment]
Thank you @matentzn  closed!
