### ISSUE TITLE
Fix documentation for obsoletion and merge

### ISSUE THREAD

**Issue by shawntanzk** [OBOAcademy/obook#138]
@matentzn - took down notes on stuff to add for docs (note: some of these might be in already, just based off my memory for now as I cant multitask too much >.<)
Things that came out from monarch training that should be added to docs:

- [x] Merge: add alt_id (not sure if we want to standardize this? it will stop anything going wrong with GO) 
- [x] add github link to rdfs:seeAlso
- [x] has_obsolence_reason (is this specific to ontologies? I do see it is a IAO annotation so doesn't seem overly specific)
- [x] docs to note that some ontologies use 'scheduled for obsoletion on or after' - write a sentence to ask people to check
- [x] Make entity obsolete using protege
- [ ] New explainer doc describing owl:axiom stuff that gets added with owl tools + adding how to deal with this in docs - @nicolevasilevsky

**Comment by matentzn** [comment]
Yes @shawntanzk this precisely reflects what I think should be documented. 

This is also another source of interesting stuff:
- https://mondo.readthedocs.io/en/latest/developer-guide/repair-obsoleted-classes/
- https://mondo.readthedocs.io/en/latest/editors-guide/merging-and-obsoleting/

**Comment by shawntanzk** [comment]
Note to self: 
add stuff on https://robot.obolibrary.org/repair

**Comment by nicolevasilevsky** [comment]
@shawntanzk what do you mean by this?
describing owl:axiom stuff that gets added with owl tools

Is it this? 
https://mondo.readthedocs.io/en/latest/editors-guide/merging-and-obsoleting/#merge-using-owltools

I don't know if this would work for other ontologies, or if something needs to be set up to use owltools in this way. @shawntanzk or @matentzn do either of you know? It's pretty handy. :)

**Comment by nicolevasilevsky** [comment]
do we want the official obsoletion documentation to recommend using seeAlso or [IAO:0000233](http://purl.obolibrary.org/obo/IAO_0000233) term tracker?
@cmungall @balhoff @matentzn

**Comment by shawntanzk** [comment]
> Is it this?
https://mondo.readthedocs.io/en/latest/editors-guide/merging-and-obsoleting/#merge-using-owltools

yes :) I don't use that method so would need help with that. owltools should be packaged with ODK so I think it is safe for ODK ontologies. 

> do we want the official obsoletion documentation to recommend using seeAlso or [IAO:0000233](http://purl.obolibrary.org/obo/IAO_0000233) term tracker?

I think using seeAlso pointing to github ticket is a good idea :) 

>  depending on our decision, we may want to update this section in the doc (ie we don't want to add a GitHub link in the comment field)

I added that part so people using the wizard will also add ticket link no matter what, but happy to remove that and change to a manual add to seeAlso to it

**Comment by matentzn** [comment]
[IAO:0000233](http://purl.obolibrary.org/obo/IAO_0000233) should be used universally!

**Comment by matentzn** [comment]
https://github.com/information-artifact-ontology/ontology-metadata/issues/102

**Comment by nicolevasilevsky** [comment]
@shawntanzk do we need a separate ticket to package this owl tools merge command with ODK?

I think this ticket is otherwise done?

**Comment by shawntanzk** [comment]
I think we can close this ticket, thanks so much for all your help. 

> @shawntanzk do we need a separate ticket to package this owl tools merge command with ODK?

I'm not sure how the best way to do this is, as technically what is written there makes sense - it just needs owltools to be installed. We can write it in ODK way, but I think that's also not right - it excludes ontologies that do not use ODK. Personally I think its ok to leave it as is but add a owltool prereq with a link?

**Comment by nicolevasilevsky** [comment]
Ok, that makes sense. 

It looks like we have a how to page on merging that includes using owl tools:
https://oboacademy.github.io/obook/howto/merge-terms/#merge-using-owltools

I am made a small revision to the merge doc to install docker, which has owltools:
https://github.com/OBOAcademy/obook/pull/243

**Comment by nicolevasilevsky** [comment]
Closing - I think everything is done.
