### ISSUE TITLE
Broken link to Appendix

### ISSUE THREAD

**Issue by paulacalipho** [OBOAcademy/obook#181]
On the following page the link to "Appendix" on line 69 is broken
**Page**: https://github.com/OBOAcademy/obook/blob/master/docs/lesson/contributing-to-obo-ontologies.md
**Broken link**: https://github.com/OBOAcademy/obook/blob/master/04-OntologyTheory/appendix.md

**Comment by matentzn** [comment]
Thank you :) Should be fixed now!

**Comment by paulacalipho** [comment]
Thanks for taking care. 
The link to "Appendix":
works from the page: https://github.com/OBOAcademy/obook/blob/master/docs/lesson/contributing-to-obo-ontologies.md
but does not work from the page https://oboacademy.github.io/obook/lesson/contributing-to-obo-ontologies/#branch

**Comment by matentzn** [comment]
Are you sure? it works for me! Maybe refresh the page in the browser?

**Comment by paulacalipho** [comment]
I open a new private window and it works. Thanks and sorry
