### ISSUE TITLE
Create seperate document to write a good term request

### ISSUE THREAD

**Issue by matentzn** [OBOAcademy/obook#187]
Right now, guidelines for writing good term requests are buried here:

https://oboacademy.github.io/obook/lesson/ontology-term-use/#7-making-term-requests-to-existing-ontologies

I think we should have a separate guide for making a great term request. Any volunteers?

**Comment by nicolevasilevsky** [comment]
I can do it!

**Comment by nicolevasilevsky** [comment]
done

**Comment by matentzn** [comment]
I will reopen this with a few requests for changes:

- move this "lesson" to howto (lesson is not diataxis and should be reserved for very macroscopic units of teaching)
- Revise the content carefully to be 100% general (no Mondo specific stuff like OMIM)
- Add a more clear guide on what to do **before** requesting a term and add that earlier in the text. This text we have now is too short and hard to understand. This should be understandable by a database curator that has never heard of ontologies! How will they check "synonym". What is a "scope"?
