### ISSUE TITLE
Provide a list of  things we should have in our OBO set-up

### ISSUE THREAD

**Issue by ValWood** [OBOAcademy/obook#197]
Is there a list of things we should have in our Protege  set-up?

OBO plugin
Elk plug-in. 
Anything else?

**Comment by matentzn** [comment]
@bvarner-ebi this is a quite important page to add to the curator pathway:

"Assembling the Ontology Curator Toolkit: essential tools to install before getting started"

Would you be able to create such a page? You are the freshest with having been through that process! :)

**Comment by matentzn** [comment]
@ValWood can you review the two pages @bvarner-ebi and see if they make you happy?

**Comment by ValWood** [comment]
Only missing that the obo plug-in (required to  get the correct  obsoletion  workflow  IIRC?)

**Comment by bvarner-ebi** [comment]
@ValWood, I don't recall installing an OBO plug-in and have obsoleted terms before. Do you have a link to this plug-in I can review?

**Comment by ValWood** [comment]
@manulera

**Comment by manulera** [comment]
@ValWood This is the comment that mentioned it:

https://github.com/pombase/fypo/issues/4151#issuecomment-1164080558

**Comment by manulera** [comment]
Hi @ValWood so the plugin for the obsoletion is `OBO annotations editor`. You can install it in `File > Check for plugins...`

**Comment by matentzn** [comment]
I think there are a few wires crossed in the thread here.

@nicolevasilevsky can you figure out if it is necessary to install this plugin to obsolete a term or not? If the answer is no, then we should figure out why @manulera had to install it to get the option to show up in his protege. This will then determine what we need to add to the OBOOK guide.

**Comment by nicolevasilevsky** [comment]
I double-checked and I indeed have the org.protege.oboeditor.jar plugin.

@manulera Could you please do a PR to add instructions to install this plugin? Thanks!

**Comment by manulera** [comment]
Hi @nicolevasilevsky happy to do it, where should that go? In the obsoletion page, or in a separate page (installing obo plugin or something like that?) I did not see an "installing protege" or plugin tutorial.

https://oboacademy.github.io/obook/howto/obsolete-term/

**Comment by matentzn** [comment]
I would advocate a new  "set up protege" page which outlines the whole process, i.e. downloading protege, installekn ELK, installing obo editors and potentially change the memory. thank link it from https://oboacademy.github.io/obook/pathways/ontology-curator-go-style/

**Comment by nicolevasilevsky** [comment]
@manulera and @matentzn I created a page here:
https://oboacademy.github.io/obook/howto/set-up-protege/

@manulera could you please add the instructions about the obo plugin? thanks!

**Comment by nicolevasilevsky** [comment]
@manulera could you include in the instructions:

to check for the plugin in your Protege, type the following in the terminal:
`~ % cd ~/.Protege `
`Protege % open .`

**Comment by manulera** [comment]
Hi @nicolevasilevsky @matentzn I have added the section in this PR:

https://github.com/OBOAcademy/obook/pull/225

Regarding this:
> to check for the plugin in your Protege, type the following in the terminal:

I did not include it, since at least in my Protege installation, plugins might be in different places, and I wonder what the paths are in windows machines:

```
/Applications/Protégé.app/Contents/Java/plugins -> This is were the OBO plugin is
~/.Protege/plugins/
```

If the only purpose is to check the installed packages, this should do:

https://github.com/OBOAcademy/obook/blob/59c519d16e5dc2a9aa8598f68a6c7d283f4e83ce/docs/howto/set-up-protege.md?plain=1#L62

**Comment by nicolevasilevsky** [comment]
Ah, yes, that works- thanks @manulera!

**Comment by manulera** [comment]
We can close then?

**Comment by nicolevasilevsky** [comment]
yes! thanks @manulera!
