### ISSUE TITLE
Changes from xsd:string after switching from obo to owl format

### ISSUE THREAD

**Issue by manulera** [OBOAcademy/obook#206]
Hi @matentzn following the comment below

https://github.com/pombase/fypo/issues/4180#issuecomment-1171151308

I have switched to storing the ontology we edit in owl format. When I make some changes indeed the git diff is much more manageable, so thanks for that.

I noticed that in the git diff some annotations have changed (`^^xsd:string` is removed from the target of `oboInOwl#hasDbXref`). Is this normal / ok?

```diff
-AnnotationAssertion(Annotation(<http://www.geneontology.org/formats/oboInOwl#hasDbXref> "GO:0072691"^^xsd:string) Annotation(<http://www.geneontology.org/formats/oboInOwl#hasDbXref> "GOC:mah"^^xsd:string) <http://www.geneontology.org/formats/oboInOwl#hasExactSynonym> <http://purl.obolibrary.org/obo/FYPO_0000626> "abnormal premeiotic DNA replication initiation"^^xsd:string)
+AnnotationAssertion(Annotation(<http://www.geneontology.org/formats/oboInOwl#hasDbXref> "GO:0072691"^^xsd:string) Annotation(<http://www.geneontology.org/formats/oboInOwl#hasDbXref> "GOC:mah") <http://www.geneontology.org/formats/oboInOwl#hasExactSynonym> <http://purl.obolibrary.org/obo/FYPO_0000626> "abnormal premeiotic DNA replication initiation"^^xsd:string)
```

**Comment by manulera** [comment]
Hello,

It seems that the recipe is missing from the odk image that my run.sh uses. Error:

```
fypo.Makefile:55: warning: overriding recipe for target 'prepare_release'
Makefile:171: warning: ignoring old recipe for target 'prepare_release'
make: *** No rule to make target 'normalise_xsd_string'.  Stop.
```

Should I run the code below? Also in that answer

```
sed -i '' -E "s/Annotation[(](oboInOwl[:]hasDbXref [\"][^\"]*[\"])[)]/Annotation(\1^^xsd:string)/g" fypo-edit.owl
```

**Comment by matentzn** [comment]
yes, sorry, this is not part of ODK.. This is a custom baked solution.. Can you try the "manual" non-ODK versions?

**Comment by manulera** [comment]
Solved for FYPO in https://github.com/pombase/fypo/pull/4191
