### ISSUE TITLE
obook [Installing ELK 0.5 Protege] issues

### ISSUE THREAD

**Issue by ar-ibrahim** [OBOAcademy/obook#212]
https://oboacademy.github.io/obook/howto/installing-elk-in-protege/

* ELK Reasoner 0.5 was updated using Approach 2 (didn't seem to work using Approach 1).
* The video showing how to install Elk on a Mac has been deleted.

**Comment by nicolevasilevsky** [comment]
thanks for reporting @ar-ibrahim. I'll try to locate the video or I'll record a new one
