### ISSUE TITLE
embedded iframe videos do not work with YouTube videos

### ISSUE THREAD

**Issue by nicolevasilevsky** [OBOAcademy/obook#220]
For example, if I add this to a file, it says that YouTube cannot connect (or something like that)

<iframe src="https://www.youtube.com/watch?v=kE_50AzpuB8" width="640" height="480" allow="autoplay"></iframe>

**Comment by matentzn** [comment]
```
<iframe width="560" height="315" src="https://www.youtube.com/embed/kE_50AzpuB8" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
```

<iframe width="560" height="315" src="https://www.youtube.com/embed/kE_50AzpuB8" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

If you are on the video, click on Share, then "embed" then copy.

**Comment by nicolevasilevsky** [comment]
thanks @matentzn, I'll try this

**Comment by nicolevasilevsky** [comment]
it worked! yay!
https://oboacademy.github.io/obook/howto/switching-ontologies/

I love the way the embedded videos look.
