### ISSUE TITLE
Escaping characters

### ISSUE THREAD

**Issue by manulera** [OBOAcademy/obook#228]
I could add this to some page:

## Escaping `'` characters in logical definitions

When a GO term contains `'` in its name (e.g. `RNA-directed 5'-3' RNA polymerase activity`), when you enter it in the logical definition window (even if you auto-complete with tab), Protege won't let you accept because you have introduced extra quotes. You can escape them with `\`. As in Protegé 5.5, the `\` characters will show up in the logical definition, and when hovering over the term in the logical definition, you won't be able to click on it and be redirected to the right go term. However, when you save the relationship is saved correctly. You can double-check by going to the `fypo-edit.owl` file and seeing that the GO-term (or any term) is mentioned in a relationship.

**Comment by manulera** [comment]
@matentzn

**Comment by nicolevasilevsky** [comment]
That would be great @manulera. I just ran into that problem yesterday, actually!

**Comment by manulera** [comment]
Where should this section go?

**Comment by matentzn** [comment]
`reference/protege-tips.md`?

**Comment by manulera** [comment]
I went for `protege-faw.md` like for git.

https://github.com/OBOAcademy/obook/pull/229

**Comment by nicolevasilevsky** [comment]
@manulera can this be closed?

**Comment by manulera** [comment]
Closed with https://github.com/OBOAcademy/obook/pull/229
