### ISSUE TITLE
GitHub actions for robot diff on release

### ISSUE THREAD

**Issue by manulera** [OBOAcademy/obook#237]
Hello,

From a conversation on Slack I got some info on how to implement github actions to automatically include `robot diff` as comment whenever a PR is made into master. I am implementing this for FYPO, and I would be happy to write a howto page in the site about it. Would this fit somewhere in the page?

**Comment by nicolevasilevsky** [comment]
Sounds great @manulera.
Could you just create a new page under docs/howto

Could you also update mkdocs.yml so the new page shows up in the left hand nav bar.

Let me know if I can help with anything.

Thanks!
