### ISSUE TITLE
fix broken links

### ISSUE THREAD

**Issue by nicolevasilevsky** [OBOAcademy/obook#252]
run a link checker (like https://www.deadlinkchecker.com/website-dead-link-checker.asp) to check for dead links and fix as needed

Here is a list of broken links:
https://docs.google.com/spreadsheets/d/1s-DFiOFRZxByikgKx8j0S4wOfB7ofLQxA4S1-WKR2X4/edit#gid=0

**Comment by caufieldjh** [comment]
Working on this now - see https://github.com/caufieldjh/obook/tree/fix-links

**Comment by katiermullen** [comment]
Working on this now.

**Comment by matentzn** [comment]
Will close now, a general ticket like this will never be addressed
