### ISSUE TITLE
EQ and SubClassOf

### ISSUE THREAD

**Issue by megbalk** [OBOAcademy/obook#264]
**Tutorial Request:**
Rules around making logical definitions.

A brief description of what you would like to be taught.
Understanding when to make a logical definition that is an EQ statement or only use SubClassOf axioms.

**Suggested materials**

**Your nano-attribution (ORCID)**

**Comment by nicolevasilevsky** [comment]
Good idea @megbalk, this would be very helpful

**Comment by matentzn** [comment]
Duplicate with https://github.com/OBOAcademy/obook/issues/32?

**Comment by megbalk** [comment]
It sure is! Sorry about that.
