### ISSUE TITLE
Lesson: add note on switching ontologies in Protege

### ISSUE THREAD

**Issue by matentzn** [OBOAcademy/obook#27]
- Documenting the last ID used before switching ontologies
- Screenshot New Entities Tab: remember setting setting: remember last ID across Protege session

**Comment by nicolevasilevsky** [comment]
add a 'how to' guide

**Comment by nicolevasilevsky** [comment]
https://github.com/OBOAcademy/obook/blob/master/docs/howto/switching_ontologies.md
