### ISSUE TITLE
Review OBO Academy lessons and fix typos, etc

### ISSUE THREAD

**Issue by nicolevasilevsky** [OBOAcademy/obook#292]
As part of the [OBO Academy hackathon](https://oboacademy.github.io/obook/lesson/hackathon/), we'd like to have folks review our existing lessons and make edits and fixes.

Lessons to review:
- [ ] Contributing to OBO ontologies: https://oboacademy.github.io/obook/lesson/contributing-to-obo-ontologies/
- [x] #303
- [ ] Project Ontology Development: https://oboacademy.github.io/obook/tutorial/project-ontology-development/
- [ ] Analysing Linked Data: https://oboacademy.github.io/obook/lesson/analysing-linked-data/
- [ ] Automating Ontology Workflows: https://oboacademy.github.io/obook/lesson/automating-ontology-workflows/
- [x] #301
- [x] Ontology Design: https://oboacademy.github.io/obook/lesson/ontology-design/
- [x] #315
- [ ] Modelling with Object Properties: https://oboacademy.github.io/obook/lesson/modelling-with-object-properties/
- [x] Ontology Term Use: https://oboacademy.github.io/obook/lesson/ontology-term-use/
- [ ] RDF Fundamentals: https://oboacademy.github.io/obook/lesson/rdf/
- [x] #304

**Comment by matentzn** [comment]
Too general now, lets call this done!
