### ISSUE TITLE
Need how to guide: how to redirect a purl to OLS instead of ontobee

### ISSUE THREAD

**Issue by nicolevasilevsky** [OBOAcademy/obook#295]
**Tutorial Request:**
how to guide on how to redirect a PURL to OLS instead of ontobee, for example

http://purl.obolibrary.org/obo/VBO_0011418 redirects to ontobee, it would be preferred if it redirected to OLS.

Does anyone know how to change the redirect?

**Comment by matentzn** [comment]
Here is the tutorial @jamesaoverton wrote: https://github.com/OBOFoundry/purl.obolibrary.org#custom-term-browsers

I would kind of like to not duplicate that kind of very technical content in OBOOK. You can create a page with a link to the purl config documentation if you want, and make a PR on the PURL config documentation if something about it is unclear.

**Comment by matentzn** [comment]
This is documented on the PURL docs in OBO, does not belong here
