### ISSUE TITLE
Add a status indicator for lessons and tutorials

### ISSUE THREAD

**Issue by matentzn** [OBOAcademy/obook#307]
Pages in OBOOK have a wide variety of quality. I would suggest adding a status flag under the lesson title that gives a sense of how mature a lesson actually is. I would suggest the following "maturity index"

<img src="https://img.shields.io/endpoint?url=https%3A%2F%2Fraw.githubusercontent.com%2FOBOAcademy%2Fobook%2Fmaster%2Fdocs%2Fresources%2Fobook-badge-construction.json" />
<img src="https://img.shields.io/endpoint?url=https%3A%2F%2Fraw.githubusercontent.com%2FOBOAcademy%2Fobook%2Fmaster%2Fdocs%2Fresources%2Fobook-badge-draft.json" />
<img src="https://img.shields.io/endpoint?url=https%3A%2F%2Fraw.githubusercontent.com%2FOBOAcademy%2Fobook%2Fmaster%2Fdocs%2Fresources%2Fobook-badge-final.json" />

**Comment by matentzn** [comment]
Done: https://oboacademy.github.io/obook/reference/obook-maturity-indicator/

**Comment by shawntanzk** [comment]
This is awesome! such a good idea! thanks @matentzn :)

**Comment by matentzn** [comment]
Thanks :)
