### ISSUE TITLE
Bad link from maturity indicator images to maturity indicator page

### ISSUE THREAD

**Issue by nlharris** [OBOAcademy/obook#322]
For example, if you click the maturity indicator on https://oboacademy.github.io/obook/lesson/contributing-to-obo-ontologies/, it goes to https://oboacademy.github.io/obook/lesson/reference/obook-maturity-indicator
but should go to
https://oboacademy.github.io/obook/reference/obook-maturity-indicator/

The html has
href="../../reference/obook-maturity-indicator/"
I guess it should be
href="../../../reference/obook-maturity-indicator/"
(or change to an absolute URL, but hat also has disadvantages)

**Comment by matentzn** [comment]
Thank you @nlharris 

Due to the problem that you can never know for sure which level in the page you are, I updated the link (and the example snippet) to use an absolute URL..
