### ISSUE TITLE
mermaid graphs are not rendering

### ISSUE THREAD

**Issue by balhoff** [OBOAcademy/obook#333]
Nice mermaid figures in here:

https://github.com/OBOAcademy/obook/blob/master/docs/explanation/taxon-constraints-explainer.md

Come out as source code in here:

https://oboacademy.github.io/obook/explanation/taxon-constraints-explainer/

**Comment by matentzn** [comment]
@souzadevinicius can you fix this? You know how it's done! Thanks!

**Comment by balhoff** [comment]
@sujaypatil96 pointed out to me that there is a plugin for this: https://github.com/fralau/mkdocs-mermaid2-plugin
