### ISSUE TITLE
Plan 2022.02.21: OBO Academy Clinic

### ISSUE THREAD

**Issue by matentzn** [OBOAcademy/obook#339]

**Comment by nicolevasilevsky** [comment]
I am interested in all of these topics that @matentzn suggested:
1) semantic similarity - what kinds are there, how do they work? 
2) How does OBO Operations Committee review new ontologies? 
3) How do I decide if something is a close or exact match (mapping issue)?

**Comment by caufieldjh** [comment]
Re: semantic similarity, what are some examples of values corresponding with biological relationships in non-obvious ways? 
It's often been used to compare GO terms, but how else?

**Comment by matentzn** [comment]
Show quick demo of SPARQL Notebook.
