### ISSUE TITLE
Plan 2023.02.22: Ubergraph and SSSOM at Ontology Summit 2023

### ISSUE THREAD

**Issue by matentzn** [OBOAcademy/obook#344]
[Summit plan](https://oboacademy.github.io/obook/courses/ontology-summit-2023/)

## Current schedule

Remember everyone to leave 3 -5 minutes for questions in each unit

09:00am: [Ubergraph: integrating OBO ontologies into a unified semantic graph](https://docs.google.com/presentation/d/1RhlZY4Yb_SDHKq3pdqIBmENr6oX7YSNmbk60Jl3JF_0/edit?usp=sharing) (incl 5 min for questions)
09:35am: [SSSOM - Open, FAIR and standardised mappings for ontologies, controlled vocabularies and database entities](https://docs.google.com/presentation/d/1_TuimFiJ_7VP0ZFkQrHYky_ktFZc981Vse0-_hZjKtc/edit#slide=id.g167f28e52df_0_74) (including 5 min for questions)

## Tutors

@balhoff   
@matentzn

## Todos

- [ ] All taught units have associated documentation pages
- [ ] Schedule is finished

**Comment by matentzn** [comment]
@balhoff does this work for you? Or shall we scrap DOSDP in favour of a longer Ubergraph session?

**Comment by balhoff** [comment]
I did the Ubergraph presentation within 30 minutes at ICBO; I don't think I have much else to add to it at the moment.

**Comment by matentzn** [comment]
Great, I just learned the day is only 60 minutes, so lets do 30 min Ubergraph, 5 min questions, 20 min SSSOM, 5 min questions.

**Comment by matentzn** [comment]
@balhoff I linked my slides above. Do you have a slide deck yet we can share with James to write the announcement?

**Comment by balhoff** [comment]
@matentzn I linked my slides.

**Comment by matentzn** [comment]
This is finished, and delivered!
