### ISSUE TITLE
Nested bullets not correctly converted from MarkDown to oBook

### ISSUE THREAD

**Issue by dosumis** [OBOAcademy/obook#380]
There is a problem with numbers and indentation in conversion to the oBook.  

e.g. 

https://oboacademy.github.io/obook/howto/merge-terms/

<img width="1268" alt="image" src="https://user-images.githubusercontent.com/112839/221163719-067b235a-ebbf-4638-9e4a-aac9a0c7f41a.png">

--> 

<img width="709" alt="image" src="https://user-images.githubusercontent.com/112839/221163552-4dfbd35e-8537-4504-bdab-4f266039b649.png">

Guidance is needed for writing Markdown for conversion (or added [here](https://oboacademy.github.io/obook/contributing/) if not already in place) and affected docs should be updated.

**Comment by balhoff** [comment]
@dosumis you might be running into the same issue I did: #346

The short answer is be sure to use 4 spaces for indentation, even though the GitHub preview indents correctly with 2 spaces.

**Comment by matentzn** [comment]
Fixed that page now.
