### ISSUE TITLE
Tutorial 13.06.2023: Subclass and Equivalent class statements

### ISSUE THREAD

**Issue by matentzn** [OBOAcademy/obook#384]
This tutorial will build on https://oboacademy.github.io/obook/explanation/intro-to-ontologies/ and provide a deep dive into the use of subClassOf and equivalentClasses statements in OWL, including existential restrictions. The tutorial will be delivered by @henrietteharmse.

Note that the date is not fixed yet - it could happen also two weeks earlier, depending on whether a conflicting event takes place or not.

**Comment by henrietteharmse** [comment]
I will be away at that time. Can do 2 weeks earlier.

**Comment by matentzn** [comment]
Alright, noted - we will coordinate this a bit closer to the time. Thanks for letting me know!

**Comment by matentzn** [comment]
The May meetings are all cancelled - I moved you to the first June meeting (13th June). It seems far off but in the end, it will come faster than the wind. Could you do that one?

**Comment by henrietteharmse** [comment]
Should be fine!
