### ISSUE TITLE
move Ontology User Pathway to Reference

### ISSUE THREAD

**Issue by nicolevasilevsky** [OBOAcademy/obook#435]
We recently created the Ontology user pathway (https://oboacademy.github.io/obook/pathways/ontology-user/), but this is not so much a pathway where you do this, then that, but more of a collection of resources for ontology users.

I suggest we move it to the Reference section, rather than Pathway.

What do other's think?

**Comment by sbello** [comment]
Agree

**Comment by nlharris** [comment]
I agree too. I have to admit I’m not totally sure what a “pathway” is in this context but i would imagine it’s some sequence of things to learn. That ontology-user page is not that; it’s, as you note, a collection of resources.
