### ISSUE TITLE
SPARQL tutorial

### ISSUE THREAD

**Issue by shawntanzk** [OBOAcademy/obook#49]
currently SPARQL tutorial is based on https://medium.com/virtuoso-blog/dbpedia-basic-queries-bc1ac172cc09 
While it is useful, it is really difficult to take this knowledge to OBO ontologies
Would be really useful to develop a tutorial on how to use SPARQL in OBO ontologies going through examples of what can be done etc.

**Comment by matentzn** [comment]
Mention @joeflack4 observation of FILTER vs VALUES speed.

**Comment by matentzn** [comment]
This is done https://oboacademy.github.io/obook/tutorial/sparql/ and scattered across a few linked pages
