### ISSUE TITLE
Glossary is incomplete

### ISSUE THREAD

**Issue by cmungall** [OBOAcademy/obook#63]
https://github.com/OBOAcademy/obook/blob/master/docs/reference/glossary.md

An OBO-centric glossary of concepts would be incredibly useful.

 - Should we crowd source this a bit more? I tend to think that it should be a few people to stay coherent
 - Will it become hard to maintain, like a large ontology? 
 - What should the scope be? Should it for example include all concepts in OWL (restriction, disjointness, QCR, GCI, TBox, ABox)? Or should these be in a specialized glossaries?
 - should we consider a full blown skos and a vocabulary management tool? Or a wikidata/wikipedia layer?

**Comment by nlharris** [comment]
Overlaps with #210
