### ISSUE TITLE
Fix Mondo reasoning example in 'contributing to obo ontologies' tutorial

### ISSUE THREAD

**Issue by dosumis** [OBOAcademy/obook#79]
The modelling approach suggested in the tutorial [here](https://github.com/OBOAcademy/obook/blob/master/docs/lesson/contributing_to_obo_ontologies.md#add-annotations-and-logical-definition-equivalence-axiom-to)  is wrong.

Tutorial text says:
![image](https://user-images.githubusercontent.com/112839/146181850-2e185fde-77ad-4f90-938f-d2143496f159.png)

But it is _not_ safe to add this subClassOf axiom unless all instances of farmer's lung disease are caused by 'Penicillium glabrum'.  This is well illustrated by the automated classification it gets under 'cork-handler's disease' if you follow the tutorial. This has the definition:

![image](https://user-images.githubusercontent.com/112839/146182611-4a6e87f6-c5e6-4efe-a5d0-99bb3aebe6ff.png) 

In this case, the disease is defined as a reaction to 'Penicillium glabrum', so the restriction is justified and the classification under 'fungal lung disease' is correct.  But classification of farmer's lung disease as a cork handler's disease is clearly not.

CC @nicolevasilevsky @matentzn  - I think we need to fix this example in the tutorial.

**Comment by nicolevasilevsky** [comment]
thanks @dosumis, I will fix this in the tutorial asap

**Comment by nicolevasilevsky** [comment]
I am just going to delete these improper instructions for now. I'll work on adding a proper example later.
