### ISSUE TITLE
Using ODK with DOSDPs

### ISSUE THREAD

**Issue by ramonawalls** [OBOAcademy/obook#83]
**Tutorial Request:**

Many ontologies use Dead Simple Ontology Design Patterns (DOSDP) to create terms. ODK has an option to specify that you want to use them (`use_dosdps: true`), but beyond that, it is not clear what to add to your project's YAML file so that it will configure your Makefile appropriately for patterns. For example, I think that the list of patterns should go under `pattern_group`, but without examples, it is hard to figure out how to list the different patterns there.  

**Suggested materials**
What I really need is documentation for the different options that I can use in my YAML file, but I do think a full tutorial on working with patterns (building off https://oboacademy.github.io/obook/tutorial/dosdp_template/) would be broadly useful. 

I'm happy to contribute more to the tutorial, if I can figure out how to do it. :)

**Your nano-attribution (ORCID)**
https://orcid.org/0000-0001-8815-0078

**Comment by jamesaoverton** [comment]
I assigned this to Nico, since he's the best one to handle it. Unfortunately he's offline until late January so there will be a delay. If someone else wants to tackle this sooner, please do!

**Comment by matentzn** [comment]
This is now covered here https://oboacademy.github.io/obook/tutorial/dosdp-odk/
