### ISSUE TITLE
Tweak to RENCI SPARQL endpoint URL?

### ISSUE THREAD

**Issue by ddooley** [OBOAcademy/obook#88]
RENCI Ubergraph Endpoint mentioned in https://oboacademy.github.io/obook/tutorial/sparql/ triggers a download of an rdf file, but maybe the website ubergraph app was intended? If so then https://stars-app.renci.org/ubergraph/sparql should be #sparql anchored https://stars-app.renci.org/ubergraph#sparql  ?

**Comment by ddooley** [comment]
Turns out this will be deprecated soon.  See https://github.com/INCATools/ubergraph/issues/37

**Comment by matentzn** [comment]
Thanks @ddooley for the report, changed the link to yasgui instead.
