### ISSUE TITLE
Incorporate & update generic OBO editor docs from odk/docs

### ISSUE THREAD

**Issue by dosumis** [OBOAcademy/obook#92]
These should live under 

HowToGuides/obo_editor_docs:

CreateNewTerm.md
DeletingAssertedSubClasses.md
MergeTerms.md
NewSlim.md
NewSlimTerm.md
ObsoleteTerm.md
Synonyms.md
TaxonRestriction.md
TermComments.md

We need to link these to theory/reference docs.

**Comment by matentzn** [comment]
Some of these should go under reference.

**Comment by matentzn** [comment]
Also gut the ODK repo stuff:

https://github.com/INCATools/ontology-development-kit/blob/master/docs

I.e. the goal is to get rid of it in favour of obook.

**Comment by matentzn** [comment]
Also while you are at it, gut the ODK docs and delete them slowly slowly.

**Comment by shawntanzk** [comment]
Will start working on this branch: https://github.com/OBOAcademy/obook/tree/migration-from-odk-docs
Currently just moved the above there, have not done any sorting and linking etc.
Just dropping this link here in case anyone wants to simultaneously work

**Comment by dosumis** [comment]
> Some of these should go under reference.

I would like the editor relevant docs to be grouped in some way.  Basically, I'm thinking of everything that an editor would need whilst working in Protege  - maybe with the addition of how to add a foreign term not yet in imports. I think it is potentially confusing and intimidating to new editors for these to be mixed in with more technical docs(pipline docs, guides to ROBOT, SPARQL etc.).  I guess this could be achieved via an indexing document rather than location. Or maybe we need a level under HowTo, reference etc that groups by role?

**Comment by shawntanzk** [comment]
@dosumis my understanding of the plan is to put everything in one of these 4 docs categories, then have "pathways" with links for each roles (editors, pipeline developers, etc.) that gather what is needed in the end in a structured way.

**Comment by shawntanzk** [comment]
> Or maybe we need a level under HowTo, reference etc that groups by role?

personally would prefer the above suggestion of linking by roles through a documents with links than to do it in the index structure

**Comment by matentzn** [comment]
Let's try both!

**Comment by shawntanzk** [comment]
Migration completed, any further issues should be made in individual tickets/PRs
