### ISSUE TITLE
Add role-based getting started pages.

### ISSUE THREAD

**Issue by dosumis** [OBOAcademy/obook#94]
These should be brief and include a ordered set of links with brief descriptive text covering topics for each of the roles described here:  
https://oboacademy.github.io/obook/getting_started/#the-different-roles-of-obo-semantic-engineering

**Comment by matentzn** [comment]
Super cool, yeah, I would suggest separate "pathway" pages for each role, linked from the general getting started page!

@shawntanzk ping brad perhaps to help with a

**Comment by shawntanzk** [comment]
pinging @bvarner-ebi

**Comment by shawntanzk** [comment]
Currently pathways merged in - needs edits, but will close this for now - edits should be made as more specific requests
