### ISSUE TITLE
Filenames: snake, camel, kebap or pascal

### ISSUE THREAD

**Issue by matentzn** [OBOAcademy/obook#99]
This may have consequences everywhere, so lets take a vote on [cases in filenames](https://winnercrespo.com/naming-conventions/) in the obook (and by extension, all documentation) before it gets too chaotic:

- 👍 : This is PascalCase: RobotTutorial.md
- 👀 : This is camelCase: robotTutorial.md
- 🚀 : This is snake_case: robot_tutorial.md
- 🎉 : This is kebap-case: robot-tutorial.md

I personally favour `snake_case` as it is the least ambiguous to tools that work with filenames, with kebap-case a close second and camelCase very last.

**Comment by cthoyt** [comment]
I echo using snake case to create the least havoc during file name procesing

**Comment by cmungall** [comment]
kebab for filenames and URLs

From

https://compositecode.blog/2020/11/27/name-casing-conventions

_Kebab case is excellent for filenames, URIs, or something of that sort where spacing between the words of a file or path are important to read, but an underscore would be obfuscated by the font rendering such as with a URI._

How about just existing an existing style guide wholesale, including conventions for accent characters erc

google style guide:

https://developers.google.com/style/filenames

Recommended: avoiding-cliches.jd

Sometimes OK: avoiding_cliches.jd

Not recommended: avoidingcliches.jd

Not recommended: avoidingCliches.jd

Not recommended: avoiding-clichés.jd

**Comment by cmungall** [comment]
beware if you mix whitespace and snake case you get whitesnake case 🎸 🤘

**Comment by matentzn** [comment]
I am happy with adopting a style guide such as the one by Google you shared @cmungall 

Are there any arguments _against_ kebap case? Just so we can have a more informed vote..

**Comment by cthoyt** [comment]
Yeah actually I change my mind after what chris wrote

**Comment by jamesaoverton** [comment]
I like kebab case for filenames and URLs.

I guess I like kebab in general. But most programming languages use "-" for arithmetic, so you need to switch to underscores when files intersect with language symbols: e.g. Python packaging tools convert hyphens to underscores. Clojure lets you use kebab everywhere -- one more reason why it's the best! :smile:

**Comment by matentzn** [comment]
Massive changed, moved everything to kebap case. Thanks all.

**Comment by noelmcloughlin** [comment]
The main problem with kebap case is  `-` can and is interpreted as minus sign in various tools and programming languages. For example python/Jinja2 interpret   `{{ my-variable | tojson }}` as subtraction, then, filter operation. So in YAML I avoid kebap case since I never know if some other tool will be layered on the YAML and deduce its subtraction.

**Comment by matentzn** [comment]
Good point @noelmcloughlin! I think for files names this should still be ok though, as these will never be spelled out in a jinja template, or at least in no situation I can think off. Good pint nonetheless!
